### ISSUE TITLE
1.20.2?plugin! on modrinth

### ISSUE THREAD

**Issue by Legendmanj** [4drian3d/ClientCatcher#60]

**Comment by 4drian3d** [comment]
What?

**Comment by Legendmanj** [comment]
> What?

when is 1.20.2 update

**Comment by 4drian3d** [comment]
ClientCatcher is a proxy plugin (Velocity), it does not require specific updates every time a new version of Minecraft is released.
However, I will put the "_compatibility_" of 1.20.2 in Modrinth when I am able to test it with a 1.20.2 client, which I can't do yet because Velocity is not stable enough in 1.20.2
